apiVersion: v1
kind: ConfigMap
metadata:
  name: trainbook-config
data:
  APP_NAME: "Train Ticket Reservation System"
  APP_ENV: "openshift"
  APP_PORT: "9090"

  # Oracle Database
  DB_HOST: "oracle-db.example.com"
  DB_PORT: "1521"
  DB_SERVICE: "ORCL"
  DB_USERNAME: "RESERVATION"