<<<<<<< HEAD
apiVersion: v1
kind: Secret
metadata:
  name: trainbook-secret
type: Opaque
stringData:
=======
apiVersion: v1
kind: Secret
metadata:
  name: trainbook-secret
type: Opaque
stringData:
>>>>>>> 6f21fe0848d86e309728e7ab6dd8d7402a49751c
  DB_PASSWORD: "MANAGER"